language: php

php:
    - hhvm
    - 5.6
    - 5.5
    - 5.4

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer self-update
    - composer install --dev

before_script:
    - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
    - composer update --dev --no-interaction
    - phpenv config-rm xdebug.ini

script:
    - composer test
